.ORIG x3000
LD R0, NUMBER1 ;LOAD 1ST NUMBER
BRn STOP ;CHECK INPUT IS NOT NEG

LD R1, NUMBER2 ;LOAD 2ND NUMBER
BRn STOP ;CHECK INPUT2 IS NOT NEG


ADD R5, R1, #0 ;COPYING INPUT1 INTO R5
AND R2, R2, #0 ;REMAINDER SET TO 0
And R3, R3, #0 ;QUOTIENT SET TO 0
AND R4, R4, #0 ;MULTIPLICANT SET TO 0

NOT R2, R1 ;NOT INPUT 2 (1ST COMPLEMENT)
ADD R2, R2, #1 ;ADDING ONE FOR (2ND COMPLEMENT)

DIVIDE ADD R3, R3, #1 ;ADDING 1 EVERYTIME IT SUBSTRACT
ADD R0, R0, R2 ;SUBSTRATIC DIVIDEND WITH DIVISOR
BRN NEG ;BRANCH OUT IF NEG TO COUNT REMAINDER
BRZ ZERO ;BRANCH OUT TO STORE IF EQUALS O ZERO
BRP DIVIDE ;BRANCH UP IF POSITIVE

NEG ADD R3, R3, #-1 ;SUBSTRACT ONE TO QUOTIENT
ADD R2, R0, R1 ;CALCULATING REMAIDER
STOP STI R4, STORE_MULT; STORE MULTIPLICANT
ZERO STI R2, REMAINDER ;STORE REMAINDER
STI R3, QUOTIENT ;STORE QUOTIENT
HALT

NUMBER1 .FILL x0014 ;DECLARING VARIABLE
NUMBER2 .FILL x0003 ;DECLARING VARIABLE
STORE_MULT .FILL x3102 ;DECLARING VARIABLE
REMAINDER .FILL x3104 ;DECLARING VARIABLE
QUOTIENT .FILL x3103 ;DECLARING VARIABLE


.END